version: '3'
services:
  db_sql:
    container_name: container-sql
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
      mssql-ubuntu
    domainname:
      douglasproglima
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "14334:1433"
    cpu_count: 4